sudo: required
services:
  - docker
env:
 global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_248d61edfafe_key -iv $encrypted_248d61edfafe_iv -in service_account.json.enc -out service_account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service_account.json
  - glcoud config set project microservices01-292400
  - glcoud config set compute/zone asia-east1-a
  - gcloud container clusters get-credentials multicluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t rsmadhavan/react-test -f ./client/Dockerfile.dev

script:
  - docker run rsmadhavan/react-test npm -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master